import {
  useMapDraft,
  selectOverlaySources,
  paintSolidRegion,
} from "../draft";
import { paintTerrain } from "../../terrainPaint";
import { BBox } from "../../map/bbox";
import type { Config } from "../../map";

const draft = useMapDraft();

beforeEach(() => draft.reset());

describe("useMapDraft", () => {
  it("starts empty", () => {
    expect(draft.terrain.value.data).toBe("");
    expect(draft.mask.value.data).toBe("");
    expect(draft.background.value.data).toBe("");
    expect(draft.ladders.value).toEqual([]);
    expect(draft.layers.value).toEqual([]);
  });

  it("loadConfig then toConfig round-trips the core fields", () => {
    const config: Config = {
      terrain: { data: "T", mask: "M" },
      background: { data: "B" },
      layers: [{ data: "L", x: 1, y: 2 }],
      bbox: { left: 0, top: 0, right: 100, bottom: 50 },
      parallax: { name: "Ocean", offset: 5 },
      scale: 3,
      ladders: [{ left: 1, top: 1, right: 2, bottom: 9 }],
    };
    draft.loadConfig(config, "My map");

    expect(draft.name.value).toBe("My map");
    expect(draft.terrain.value.data).toBe("T");
    expect(draft.mask.value.data).toBe("M");
    expect(draft.advancedSettings.value.customMask).toBe(true);
    expect(draft.advancedSettings.value.scale).toBe(3);
    expect(draft.advancedSettings.value.parallaxName).toBe("Ocean");

    const out = draft.toConfig();
    expect(out.terrain.data).toBe("T");
    expect(out.terrain.mask).toBe("M");
    expect(out.background?.data).toBe("B");
    expect(out.scale).toBe(3);
    expect(out.parallax).toEqual({ name: "Ocean", offset: 5 });
    expect(out.layers).toHaveLength(1);
    expect(out.ladders).toHaveLength(1);
  });

  it("applyPaint sets terrain + background, clears the mask, disables custom mask, defaults parallax", () => {
    draft.applyWfc("MASKDATA", []); // a wallmask was generated first
    draft.applyPaint({ terrain: "TT", background: "BB", width: 80, height: 40 });
    expect(draft.terrain.value.data).toBe("TT");
    expect(draft.background.value.data).toBe("BB");
    expect(draft.mask.value.data).toBe("");
    expect(draft.advancedSettings.value.customMask).toBe(false);
    expect(draft.advancedSettings.value.parallaxName).toBe("Ocean");
  });

  it("setMaskImage stores the data as a hidden mask", () => {
    draft.setMaskImage("MASKDATA");
    expect(draft.mask.value.data).toBe("MASKDATA");
    expect(draft.mask.value.visible).toBe(false);
  });

  it("applyWfc sets the mask, enables custom mask, and populates ladders", () => {
    draft.applyWfc("MASKDATA", [
      { x: 10, y: 20, width: 6, height: 30 },
      { x: 40, y: 20, width: 6, height: 30 },
    ]);
    expect(draft.mask.value.data).toBe("MASKDATA");
    expect(draft.advancedSettings.value.customMask).toBe(true);
    expect(draft.ladders.value).toHaveLength(2);
    expect(draft.layers.value).toEqual([]);
  });

  it("applyAiAlign sets terrain, background, and a hidden mask", () => {
    draft.applyAiAlign({
      terrain: "AT", background: "AB", mask: "AM", width: 80, height: 40,
    });
    expect(draft.terrain.value.data).toBe("AT");
    expect(draft.background.value.data).toBe("AB");
    expect(draft.mask.value.data).toBe("AM");
    expect(draft.mask.value.visible).toBe(false);
  });

  it("reset clears everything", () => {
    draft.loadConfig(
      {
        terrain: { data: "T" }, layers: [], bbox: BBox.create(10, 10).toJS(),
        parallax: { name: "", offset: 0 }, scale: 6,
      },
      "x"
    );
    draft.reset();
    expect(draft.terrain.value.data).toBe("");
    expect(draft.name.value).toBe("");
    expect(draft.ladders.value).toEqual([]);
  });

  describe("selectOverlaySources", () => {
    it("uses background only for autogenerated maps", () => {
      expect(selectOverlaySources(true, true)).toEqual(["background"]);
    });

    it("falls back to terrain when autogenerated has no background", () => {
      expect(selectOverlaySources(true, false)).toEqual(["terrain"]);
    });

    it("composites background then terrain for other maps", () => {
      expect(selectOverlaySources(false, true)).toEqual(["background", "terrain"]);
    });

    it("uses terrain only when no background is present", () => {
      expect(selectOverlaySources(false, false)).toEqual(["terrain"]);
    });
  });

  describe("autogenerated flag", () => {
    it("starts false", () => {
      expect(draft.autogenerated.value).toBe(false);
    });

    it("is true after applyPaint and false after a manual terrain upload", () => {
      draft.applyPaint({ terrain: "TT", background: "BB", width: 80, height: 40 });
      expect(draft.autogenerated.value).toBe(true);
      draft.setTerrainImage("UPLOAD");
      expect(draft.autogenerated.value).toBe(false);
    });

    it("is false for applyWfc, applyAiAlign, loadConfig and reset", () => {
      draft.applyPaint({ terrain: "TT", background: "BB", width: 80, height: 40 });
      draft.applyWfc("MASK", []);
      expect(draft.autogenerated.value).toBe(false);

      draft.applyPaint({ terrain: "TT", background: "BB", width: 80, height: 40 });
      draft.applyAiAlign({ terrain: "AT", background: "AB", mask: "AM", width: 80, height: 40 });
      expect(draft.autogenerated.value).toBe(false);

      draft.applyPaint({ terrain: "TT", background: "BB", width: 80, height: 40 });
      draft.loadConfig(
        { terrain: { data: "T" }, layers: [], bbox: BBox.create(10, 10).toJS(), parallax: { name: "", offset: 0 }, scale: 6 },
        "x"
      );
      expect(draft.autogenerated.value).toBe(false);

      draft.applyPaint({ terrain: "TT", background: "BB", width: 80, height: 40 });
      draft.reset();
      expect(draft.autogenerated.value).toBe(false);
    });
  });

  describe("solid terrain overlays", () => {
    // a 6x6 map solid only in the bottom two rows
    const mapWidth = 6;
    const mapHeight = 6;
    const sampleAlpha = () => {
      const alpha = new Uint8Array(mapWidth * mapHeight);
      for (let y = 4; y < mapHeight; y++) {
        for (let x = 0; x < mapWidth; x++) alpha[y * mapWidth + x] = 1;
      }
      return alpha;
    };

    it("applyPaint stores a paint context only when the wallmask is provided", () => {
      draft.applyPaint({ terrain: "TT", background: "BB", width: 80, height: 40 });
      expect(draft.paintContext.value).toBeNull();

      const alpha = sampleAlpha();
      draft.applyPaint({
        terrain: "TT",
        background: "BB",
        width: mapWidth,
        height: mapHeight,
        alpha,
        themeOverrides: { 0: "cave" },
        seed: 7,
      });
      expect(draft.paintContext.value?.seed).toBe(7);
      expect(draft.paintContext.value?.alpha).toBe(alpha);
      expect(draft.paintContext.value?.themeOverrides).toEqual({ 0: "cave" });

      draft.reset();
      expect(draft.paintContext.value).toBeNull();
    });

    it("paintSolidRegion fills the whole box opaque, even over open sky", () => {
      const ctx = {
        alpha: sampleAlpha(),
        width: mapWidth,
        height: mapHeight,
        seed: 1,
        themeOverrides: {},
      };
      // box over the top rows, which are open sky in the source map
      const image = paintSolidRegion(ctx, { x: 1, y: 0, width: 3, height: 3 });
      expect(image.width).toBe(3);
      expect(image.height).toBe(3);
      for (let i = 3; i < image.data.length; i += 4) {
        expect(image.data[i]).toBe(255);
      }
    });

    it("paintSolidRegion matches the full re-paint at the box's map coordinates", () => {
      const ctx = {
        alpha: sampleAlpha(),
        width: mapWidth,
        height: mapHeight,
        seed: 1,
        themeOverrides: {},
      };
      const box = { x: 2, y: 1, width: 2, height: 2 };

      // reference: re-paint the whole map with the box forced solid
      const solid = Uint8Array.from(ctx.alpha);
      for (let yy = box.y; yy < box.y + box.height; yy++) {
        for (let xx = box.x; xx < box.x + box.width; xx++) {
          solid[yy * mapWidth + xx] = 1;
        }
      }
      const reference = paintTerrain({
        alpha: solid,
        width: mapWidth,
        height: mapHeight,
        ladders: [],
        seed: 1,
        themeOverrides: {},
      }).terrain;

      const image = paintSolidRegion(ctx, box);
      // top-left of the crop equals the map pixel at (box.x, box.y)
      const ri = (box.y * mapWidth + box.x) * 4;
      expect([image.data[0], image.data[1], image.data[2], image.data[3]]).toEqual([
        reference.data[ri],
        reference.data[ri + 1],
        reference.data[ri + 2],
        reference.data[ri + 3],
      ]);
    });
  });

  describe("pending overlay serialization", () => {
    it("drops layers that have a box but no data, and emits only data/x/y", () => {
      draft.layers.value.push({ data: "L", x: 1, y: 2, visible: true });
      draft.layers.value.push({
        data: "",
        x: 0,
        y: 0,
        visible: true,
        box: new BBox(3, 4, 13, 24),
      });

      const out = draft.toConfig();
      expect(out.layers).toHaveLength(1);
      expect(out.layers[0]).toEqual({ data: "L", x: 1, y: 2 });
    });
  });

  describe("resolvePendingOverlays", () => {
    it("is a no-op when no layer has a pending box", async () => {
      draft.layers.value.push({ data: "L", x: 1, y: 2, visible: true });
      await draft.resolvePendingOverlays();
      expect(draft.layers.value[0]).toEqual({ data: "L", x: 1, y: 2, visible: true });
    });

    it("confirmOverlay does nothing when the layer has no box", async () => {
      draft.layers.value.push({ data: "L", x: 1, y: 2, visible: true });
      await draft.confirmOverlay(0);
      expect(draft.layers.value[0].data).toBe("L");
      expect(draft.layers.value[0].box).toBeUndefined();
    });

    it("confirmOverlay leaves the box when there is no terrain or background to sample", async () => {
      draft.layers.value.push({ data: "", x: 0, y: 0, visible: true, box: new BBox(1, 1, 5, 5) });
      await draft.confirmOverlay(0);
      expect(draft.layers.value[0].data).toBe("");
      expect(draft.layers.value[0].box).toBeDefined();
    });
  });
});
