import { ref, shallowRef } from "vue";
import { BBox } from "../map/bbox";
import { Config, Layer, Map } from "../map";
import type { LadderInfo } from "../wfc/postProcess";
import { paintTerrain } from "../terrainPaint";
import type { ZoneInfo } from "../terrainPaint/zones";
import { logEvent } from "../../util/firebase";

interface PaintContext {
  zoneMap: Int32Array;
  zones: ZoneInfo[];
  width: number;
  height: number;
  seed: number;
}

export interface AdvancedSettings {
  bbox: BBox;
  scale: number;
  customMask: boolean;
  parallaxName: string;
  parallaxOffset: number;
}

const emptyAdvanced = (): AdvancedSettings => ({
  scale: 6,
  bbox: BBox.create(0, 0),
  customMask: false,
  parallaxName: "",
  parallaxOffset: 0,
});

const terrain = ref({ data: "", visible: false });
const mask = ref({ data: "", visible: false });
const background = ref({ data: "", visible: false });
const layers = ref<Array<Layer & { visible: boolean; box?: BBox }>>([]);
const ladders = ref<BBox[]>([]);
const advancedSettings = ref<AdvancedSettings>(emptyAdvanced());
const name = ref("");
const oldScale = ref(advancedSettings.value.scale);
const autogenerated = ref(false);
const paintContext = shallowRef<PaintContext | null>(null);

const setImage = (
  target: typeof terrain,
  data: string,
  visible: boolean
) => {
  target.value = { data, visible };
  if (advancedSettings.value.bbox.isEmpty() && data) {
    const image = new Image();
    image.src = data;
    image.onload = () => {
      advancedSettings.value.bbox = BBox.create(image.width, image.height);
    };
  }
};

const setTerrainImage = (data: string) => {
  autogenerated.value = false;
  paintContext.value = null;
  setImage(terrain, data, true);
};
const setBackgroundImage = (data: string) => setImage(background, data, true);
const setMaskImage = (data: string) => setImage(mask, data, false);

const applyWfc = (maskData: string, wfcLadders: LadderInfo[]) => {
  autogenerated.value = false;
  paintContext.value = null;
  mask.value = { data: maskData, visible: true };
  advancedSettings.value.customMask = true;
  ladders.value = wfcLadders.map(
    (l) =>
      new BBox(l.x - l.width / 2, l.y, l.x + l.width / 2, l.y + l.height)
  );
  layers.value = [];

  const image = new Image();
  image.src = maskData;
  image.onload = () => {
    advancedSettings.value.bbox = BBox.create(image.width, image.height);
  };
};

const applyPaint = (result: {
  terrain: string;
  background: string;
  width: number;
  height: number;
  zoneMap?: Int32Array;
  zones?: ZoneInfo[];
  seed?: number;
}) => {
  autogenerated.value = true;
  paintContext.value =
    result.zoneMap && result.zones
      ? {
          zoneMap: result.zoneMap,
          zones: result.zones,
          width: result.width,
          height: result.height,
          seed: result.seed ?? 1,
        }
      : null;
  terrain.value = { data: result.terrain, visible: true };
  background.value = { data: result.background, visible: true };
  // the painted terrain's alpha is the wallmask, so drop any generated mask
  mask.value = { data: "", visible: false };
  advancedSettings.value.customMask = false;
  advancedSettings.value.bbox = BBox.create(result.width, result.height);
  if (!advancedSettings.value.parallaxName) {
    advancedSettings.value.parallaxName = "Ocean";
  }
};

const applyAiAlign = (result: {
  terrain: string;
  background: string;
  mask: string;
  width: number;
  height: number;
}) => {
  autogenerated.value = false;
  paintContext.value = null;
  terrain.value = { data: result.terrain, visible: true };
  background.value = { data: result.background, visible: true };
  mask.value = { data: result.mask, visible: false };
  advancedSettings.value.bbox = BBox.create(result.width, result.height);
};

const loadConfig = (config: Config, mapName: string) => {
  autogenerated.value = false;
  paintContext.value = null;
  oldScale.value = config.scale;
  terrain.value = { data: config.terrain.data as string, visible: true };
  background.value = {
    data: (config.background?.data as string) || "",
    visible: true,
  };
  layers.value = config.layers.map((layer) => ({ ...layer, visible: true }));
  advancedSettings.value = {
    bbox: BBox.fromJS(config.bbox) || BBox.create(0, 0),
    scale: config.scale,
    customMask: !!config.terrain.mask,
    parallaxName: config.parallax.name,
    parallaxOffset: config.parallax.offset,
  };
  name.value = mapName;
  ladders.value =
    (config.ladders
      ?.map((bbox) => BBox.fromJS(bbox))
      .filter(Boolean) as BBox[]) || [];
  mask.value = config.terrain.mask
    ? { data: config.terrain.mask as string, visible: false }
    : { data: "", visible: false };
};

const toConfig = (): Config => ({
  terrain: {
    data: terrain.value.data || mask.value.data,
    mask: mask.value.data,
  },
  background: background.value.data ? { data: background.value.data } : undefined,
  layers: layers.value
    .filter((layer) => !!layer.data)
    .map((layer) => ({ data: layer.data, x: layer.x, y: layer.y })),
  bbox: advancedSettings.value.bbox,
  parallax: {
    name: advancedSettings.value.parallaxName,
    offset: advancedSettings.value.parallaxOffset,
  },
  scale: advancedSettings.value.scale,
  ladders: ladders.value,
});

const generateOverlay = async (
  box: BBox
): Promise<{ data: string; x: number; y: number }> => {
  const x = Math.round(box.left);
  const y = Math.round(box.top);
  const width = Math.max(1, Math.round(box.width));
  const height = Math.max(1, Math.round(box.height));

  // Painted maps re-texture the box as a fully solid block so the occluder
  // reads as solid terrain rather than the recessed back-wall behind it.
  const paint = paintContext.value;
  if (autogenerated.value && paint) {
    const themeId = selectOverlayTheme(paint, x, y, width, height);
    const image = paintSolidBlock(width, height, themeId, paint.seed);
    const canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;
    canvas.getContext("2d")!.putImageData(image, 0, 0);
    return { data: canvas.toDataURL(), x, y };
  }

  const sources = selectOverlaySources(
    autogenerated.value,
    !!background.value.data
  );

  const images: Record<"background" | "terrain", HTMLImageElement | undefined> = {
    background: background.value.data
      ? ((await Map.loadImage(background.value.data)) as HTMLImageElement)
      : undefined,
    terrain: terrain.value.data
      ? ((await Map.loadImage(terrain.value.data)) as HTMLImageElement)
      : undefined,
  };

  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d")!;

  for (const key of sources) {
    const image = images[key];
    if (image) {
      ctx.drawImage(image, x, y, width, height, 0, 0, width, height);
    }
  }

  return { data: canvas.toDataURL(), x, y };
};

const confirmOverlay = async (index: number) => {
  const layer = layers.value[index];
  if (!layer?.box) return;
  if (!paintContext.value && !background.value.data && !terrain.value.data) return;

  const { data, x, y } = await generateOverlay(layer.box);
  layer.data = data;
  layer.x = x;
  layer.y = y;
  layer.box = undefined;
};

const resolvePendingOverlays = async () => {
  for (let i = 0; i < layers.value.length; i++) {
    const layer = layers.value[i];
    if (layer.box && !layer.data) {
      await confirmOverlay(i);
    }
  }
};

const build = async () => {
  await resolvePendingOverlays();
  const map = await Map.fromConfig(toConfig());
  const url = URL.createObjectURL(await map.toBlob());
  setTimeout(() => window.URL.revokeObjectURL(url), 1000);
  const link = document.createElement("a");
  link.download = `${name.value || "map"}.png`;
  link.href = url;
  link.click();
  logEvent("build_map");
};

const reset = () => {
  autogenerated.value = false;
  paintContext.value = null;
  terrain.value = { data: "", visible: false };
  mask.value = { data: "", visible: false };
  background.value = { data: "", visible: false };
  layers.value = [];
  ladders.value = [];
  advancedSettings.value = emptyAdvanced();
  name.value = "";
  oldScale.value = advancedSettings.value.scale;
};

export function selectOverlaySources(
  autogenerated: boolean,
  hasBackground: boolean
): Array<"background" | "terrain"> {
  if (autogenerated) {
    return hasBackground ? ["background"] : ["terrain"];
  }

  return hasBackground ? ["background", "terrain"] : ["terrain"];
}

// The most common solid-zone theme overlapping the box; grassland (the paint
// default) when the box covers only open sky.
export function selectOverlayTheme(
  ctx: { zoneMap: Int32Array; zones: ZoneInfo[]; width: number; height: number },
  x: number,
  y: number,
  width: number,
  height: number
): string {
  const counts: Record<string, number> = {};
  const x1 = Math.min(ctx.width, x + width);
  const y1 = Math.min(ctx.height, y + height);
  for (let yy = Math.max(0, y); yy < y1; yy++) {
    for (let xx = Math.max(0, x); xx < x1; xx++) {
      const zi = ctx.zoneMap[yy * ctx.width + xx];
      if (zi < 0) continue;
      const themeId = ctx.zones[zi]?.themeId;
      if (!themeId) continue;
      counts[themeId] = (counts[themeId] ?? 0) + 1;
    }
  }

  let best = "grassland";
  let bestN = 0;
  for (const themeId in counts) {
    if (counts[themeId] > bestN) {
      best = themeId;
      bestN = counts[themeId];
    }
  }
  return best;
}

// Re-paint a fully solid block in a single theme, yielding solid terrain
// texture across the whole region (no surface band, since nothing is open sky).
export function paintSolidBlock(
  width: number,
  height: number,
  themeId: string,
  seed: number
): ImageData {
  const alpha = new Uint8Array(width * height).fill(1);
  const themeOverrides: Record<number, string> = {};
  for (let i = 0; i < 256; i++) themeOverrides[i] = themeId;

  return paintTerrain({
    alpha,
    width,
    height,
    ladders: [],
    seed,
    themeOverrides,
  }).terrain;
}

export function useMapDraft() {
  return {
    terrain, mask, background, layers, ladders, advancedSettings, name, oldScale, autogenerated, paintContext,
    setTerrainImage, setBackgroundImage, setMaskImage,
    applyWfc, applyPaint, applyAiAlign,
    loadConfig, toConfig, build, reset,
    generateOverlay, confirmOverlay, resolvePendingOverlays,
  };
}
